version: '3.3'
services:
  database:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "P@ssw0rd123"
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - projectname-mssql-data:/var/opt/mssql/data
   
volumes:
  projectname-mssql-data:
